[package]
name = "midirenderer"
version = "0.1.1"
edition = "2021"

[lib]
name = "midirenderer"
crate-type = ["cdylib"]

[dependencies]
ogg = "0.9.1"
opus = "0.3.0"
pyo3 = { version = "0.22.1", features = ["extension-module", "abi3-py38"] }
rustysynth = "1.3.1"
thiserror = "1.0.61"
